# Generated by Django 3.1.5 on 2021-02-26 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0002_auto_20210221_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary_scale_bonous',
            name='id',
        ),
        migrations.AlterField(
            model_name='salary_scale_bonous',
            name='bonus_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shift_info',
            name='office_id',
            field=models.ForeignKey(blank=True, db_column='office_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shi_office_id', to='hrm.company_office'),
        ),
    ]
