# Generated by Django 3.1.5 on 2021-02-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0003_auto_20210226_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra_allowance',
            name='allowance_id',
            field=models.CharField(blank=True, max_length=20, primary_key=True, serialize=False),
        ),
    ]
