# Generated by Django 3.1.6 on 2021-02-13 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_Class',
            fields=[
                ('class_id', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('roll_serial', models.CharField(blank=True, max_length=20)),
                ('subject_list', models.CharField(blank=True, max_length=500, null=True)),
                ('fees_list', models.CharField(blank=True, max_length=500, null=True)),
                ('app_user_id', models.CharField(blank=True, max_length=20)),
                ('app_data_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Academic_Class_Group',
            fields=[
                ('class_group_id', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('class_group_name', models.CharField(max_length=100)),
                ('subject_list', models.CharField(blank=True, max_length=500, null=True)),
                ('fees_list', models.CharField(blank=True, max_length=500, null=True)),
                ('app_user_id', models.CharField(blank=True, max_length=20)),
                ('app_data_time', models.DateTimeField(auto_now_add=True)),
                ('class_id', models.ForeignKey(blank=True, db_column='class_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cgp_class_id', to='edu.academic_class')),
            ],
        ),
        migrations.CreateModel(
            name='Academic_Year',
            fields=[
                ('academic_year', models.CharField(blank=True, max_length=30, primary_key=True, serialize=False)),
                ('app_user_id', models.CharField(blank=True, max_length=20)),
                ('app_data_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Degree_Info',
            fields=[
                ('degree_id', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('degree_name', models.CharField(max_length=200)),
                ('degree_duration', models.CharField(max_length=200)),
                ('app_user_id', models.CharField(blank=True, max_length=20, null=True)),
                ('app_data_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department_Info',
            fields=[
                ('department_id', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=200)),
                ('total_student', models.IntegerField(null=True)),
                ('total_quota', models.IntegerField(null=True)),
                ('app_user_id', models.CharField(blank=True, max_length=20, null=True)),
                ('app_data_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education_Institute',
            fields=[
                ('institute_id', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('institute_name', models.CharField(max_length=200)),
                ('degree_duration', models.CharField(max_length=200)),
                ('app_user_id', models.CharField(blank=True, max_length=20, null=True)),
                ('app_data_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Occupation_Info',
            fields=[
                ('occupation_id', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('occupation_name', models.CharField(max_length=200)),
                ('app_user_id', models.CharField(blank=True, max_length=20, null=True)),
                ('app_data_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shift_Info',
            fields=[
                ('shift_id', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('shift_name', models.CharField(max_length=200)),
                ('shift_start_time', models.CharField(max_length=100)),
                ('shift_end_time', models.CharField(max_length=100)),
                ('total_student', models.IntegerField(null=True)),
                ('total_quota', models.IntegerField(null=True)),
                ('app_user_id', models.CharField(blank=True, max_length=20, null=True)),
                ('app_data_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_roll', models.CharField(blank=True, max_length=30, null=True)),
                ('class_roll', models.CharField(blank=True, max_length=30, null=True)),
                ('app_user_id', models.CharField(blank=True, max_length=20)),
                ('app_data_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject_Type',
            fields=[
                ('subject_type_id', models.CharField(blank=True, max_length=30, primary_key=True, serialize=False)),
                ('subject_type_name', models.CharField(max_length=100)),
                ('app_user_id', models.CharField(blank=True, max_length=20)),
                ('app_data_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject_List',
            fields=[
                ('subject_id', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=150)),
                ('class_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('class_order_no', models.IntegerField(blank=True, null=True)),
                ('no_of_class', models.IntegerField(blank=True, null=True)),
                ('maximum_marks', models.IntegerField(blank=True, null=True)),
                ('minimum_marks', models.IntegerField(blank=True, null=True)),
                ('app_user_id', models.CharField(blank=True, max_length=20)),
                ('app_data_time', models.DateTimeField(auto_now_add=True)),
                ('subject_type_id', models.ForeignKey(blank=True, db_column='subject_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slt_subject_type_id', to='edu.subject_type')),
            ],
        ),
        migrations.CreateModel(
            name='Students_Info',
            fields=[
                ('student_roll', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('student_reg', models.CharField(blank=True, max_length=30, null=True)),
                ('student_name', models.CharField(max_length=200)),
                ('student_nick_name', models.CharField(max_length=200)),
                ('student_type', models.CharField(blank=True, max_length=30, null=True)),
                ('student_referred_by', models.CharField(blank=True, max_length=15, null=True)),
                ('student_father_name', models.CharField(blank=True, max_length=200)),
                ('father_email_address', models.CharField(blank=True, max_length=200)),
                ('father_phone_number', models.CharField(blank=True, max_length=20)),
                ('sms_to_father', models.BooleanField(blank=True, default=False)),
                ('student_mother_name', models.CharField(blank=True, max_length=200)),
                ('mother_email_address', models.CharField(blank=True, max_length=200)),
                ('mother_phone_number', models.CharField(blank=True, max_length=20)),
                ('sms_to_mother', models.BooleanField(blank=True, default=False)),
                ('student_blood_group', models.CharField(blank=True, choices=[('', 'Choose...'), ('A+', 'A+'), ('B+', 'B+'), ('O+', 'O+'), ('AB+', 'AB+'), ('A-', 'A-'), ('O-', 'O-'), ('B-', 'B-'), ('AB-', 'AB-')], default='', max_length=5)),
                ('student_gender', models.CharField(blank=True, choices=[('', 'Choose...'), ('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default='', max_length=5)),
                ('student_religion', models.CharField(blank=True, choices=[('', 'Choose...'), ('I', 'Islam'), ('H', 'Hinduism'), ('B', 'Buddhists'), ('C', 'Christians'), ('A', 'Animists')], default='', max_length=5)),
                ('student_marital_status', models.CharField(blank=True, choices=[('', 'Choose...'), ('M', 'Married'), ('S', 'Single'), ('D', 'Divorced'), ('O', 'Others')], default='S', max_length=5, null=True)),
                ('student_education', models.CharField(blank=True, max_length=20, null=True)),
                ('student_national_id', models.CharField(blank=True, max_length=200, null=True)),
                ('student_birth_cert', models.CharField(blank=True, max_length=200, null=True)),
                ('student_present_address', models.TextField(null=True)),
                ('student_permanent_address', models.TextField(blank=True, null=True)),
                ('student_phone', models.CharField(max_length=15, null=True)),
                ('student_email', models.CharField(blank=True, max_length=30, null=True)),
                ('student_joining_date', models.DateField(blank=True, null=True)),
                ('student_date_of_birth', models.DateField(blank=True, null=True)),
                ('student_status', models.CharField(blank=True, choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=5, null=True)),
                ('student_comments', models.CharField(blank=True, max_length=200, null=True)),
                ('emerg_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emerg_contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('emerg_contact_relation', models.CharField(blank=True, max_length=50, null=True)),
                ('emerg_contact_nid', models.CharField(blank=True, max_length=50, null=True)),
                ('app_user_id', models.CharField(blank=True, max_length=20)),
                ('app_data_time', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(blank=True, db_column='academic_year', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu_academic_year', to='edu.academic_year')),
                ('branch_code', models.ForeignKey(blank=True, db_column='branch_code', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu_branch_code', to='appauth.branch')),
                ('class_group_id', models.ForeignKey(blank=True, db_column='class_group_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu_class_group_id', to='edu.academic_class_group')),
                ('class_id', models.ForeignKey(blank=True, db_column='class_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu_class_id', to='edu.academic_class')),
                ('father_occupation_id', models.ForeignKey(blank=True, db_column='father_occupation_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu_father_occupation_id', to='edu.occupation_info')),
                ('last_institute_id', models.ForeignKey(blank=True, db_column='last_institute_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu_last_institute_id', to='edu.education_institute')),
                ('mother_occupation_id', models.ForeignKey(blank=True, db_column='mother_occupation_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu_mother_occupation_id', to='edu.occupation_info')),
                ('shift_id', models.ForeignKey(blank=True, db_column='shift_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu_shift_id', to='edu.shift_info')),
            ],
        ),
        migrations.CreateModel(
            name='Section_Info',
            fields=[
                ('section_id', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=200)),
                ('total_student', models.IntegerField(blank=True, null=True)),
                ('section_teacher_id', models.CharField(blank=True, max_length=20, null=True)),
                ('class_start_time', models.CharField(blank=True, max_length=20, null=True)),
                ('class_end_time', models.CharField(blank=True, max_length=20, null=True)),
                ('app_user_id', models.CharField(blank=True, max_length=20)),
                ('app_data_time', models.DateTimeField(auto_now_add=True)),
                ('class_id', models.ForeignKey(blank=True, db_column='class_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sec_class_id', to='edu.academic_class')),
            ],
        ),
    ]
