# Generated by Django 3.1.6 on 2021-03-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0004_auto_20210314_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(blank=True, max_length=30)),
                ('app_user_id', models.CharField(blank=True, max_length=20)),
                ('app_data_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
