# Generated by Django 3.1.6 on 2021-03-15 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0006_exam_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_Setup',
            fields=[
                ('exam_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('exam_name', models.CharField(max_length=200)),
                ('total_exam_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('minimum_pass_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('app_user_id', models.CharField(blank=True, max_length=20)),
                ('app_data_time', models.DateTimeField(auto_now_add=True)),
                ('examtype_id', models.ForeignKey(blank=True, db_column='examtype_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exs_examtype_id', to='edu.exam_type')),
            ],
        ),
    ]
