# Generated by Django 3.1.6 on 2021-03-15 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0008_exam_marks_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam_marks_details',
            name='exam_id',
        ),
    ]
