# Generated by Django 3.1.6 on 2021-03-16 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0009_remove_exam_marks_details_exam_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_Marks_Final',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_exam_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('obtain_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('result_grade', models.CharField(max_length=20)),
                ('grade_point_average', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('app_user_id', models.CharField(blank=True, max_length=20)),
                ('app_data_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
