# Generated by Django 3.1.6 on 2021-03-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0011_auto_20210316_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_info',
            name='exam_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
