# Generated by Django 3.1.6 on 2021-03-16 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0012_students_info_exam_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_info',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edu.academic_year'),
        ),
    ]
