# Generated by Django 3.1.6 on 2021-03-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0013_students_info_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_admission',
            name='add_id',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
