# Generated by Django 3.1.6 on 2021-03-16 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0014_student_admission_add_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_marks_details',
            name='exam_id',
            field=models.ForeignKey(blank=True, db_column='exam_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emd_exam_id', to='edu.exam_setup'),
        ),
        migrations.AlterField(
            model_name='exam_marks_details',
            name='student_roll',
            field=models.ForeignKey(blank=True, db_column='student_roll', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emd_student_roll', to='edu.student_admission'),
        ),
    ]
