# Generated by Django 3.1.6 on 2021-03-16 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0015_auto_20210316_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students_info',
            name='exam_id',
        ),
    ]
