# Generated by Django 3.1.6 on 2021-03-16 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0017_auto_20210316_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_admission',
            name='add_id',
        ),
    ]
