# Generated by Django 3.1.6 on 2021-03-18 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0020_auto_20210318_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_Setup',
            fields=[
                ('exam_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('exam_name', models.CharField(max_length=200)),
                ('total_exam_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('minimum_pass_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('app_user_id', models.CharField(blank=True, max_length=20)),
                ('app_data_time', models.DateTimeField(auto_now_add=True)),
                ('examtype_id', models.ForeignKey(blank=True, db_column='examtype_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exs_examtype_id', to='edu.exam_type')),
            ],
        ),
        migrations.CreateModel(
            name='Exam_Marks_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_exam_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('obtain_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('result_grade', models.CharField(max_length=20)),
                ('grade_point_average', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True)),
                ('app_user_id', models.CharField(blank=True, max_length=20)),
                ('app_data_time', models.DateTimeField(auto_now_add=True)),
                ('exam_id', models.ForeignKey(blank=True, db_column='exam_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emd_exam_id', to='edu.exam_setup')),
                ('student_roll', models.ForeignKey(blank=True, db_column='student_roll', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emd_student_roll', to='edu.students_info')),
                ('subject_id', models.ForeignKey(blank=True, db_column='subject_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emd_subject_id', to='edu.subject_list')),
            ],
        ),
    ]
