# Generated by Django 3.1.6 on 2021-03-18 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0021_exam_marks_details_exam_setup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_marks_details',
            name='exam_id',
            field=models.ForeignKey(blank=True, db_column='exam_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emd_exam_id', to='edu.students_info'),
        ),
    ]
