# Generated by Django 3.1.6 on 2021-03-18 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0022_auto_20210318_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_marks_details',
            name='exam_id',
            field=models.ForeignKey(blank=True, db_column='exam_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emd_exam_id1', to='edu.students_info'),
        ),
        migrations.AlterField(
            model_name='exam_marks_details',
            name='student_roll',
            field=models.ForeignKey(blank=True, db_column='student_roll', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emd_student_roll1', to='edu.students_info'),
        ),
        migrations.AlterField(
            model_name='exam_marks_details',
            name='subject_id',
            field=models.ForeignKey(blank=True, db_column='subject_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emd_subject_id1', to='edu.subject_list'),
        ),
    ]
