# Generated by Django 3.1.6 on 2021-03-18 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0023_auto_20210318_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_setup',
            name='examtype_id',
            field=models.ForeignKey(blank=True, db_column='examtype_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exs_examtype_id2', to='edu.exam_type'),
        ),
    ]
