# Generated by Django 3.1.6 on 2021-03-18 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0025_auto_20210318_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_marks_details',
            name='exam_id',
            field=models.ForeignKey(blank=True, db_column='exam_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emd_exam_id3', to='edu.exam_setup'),
        ),
    ]
