# Generated by Django 3.1.6 on 2021-03-18 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0026_auto_20210318_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academic_class',
            name='subject_list',
        ),
    ]
